pluginManagement {
    repositories {
        gradlePluginPortal()
        maven { url = 'https://maven.neoforged.net/releases' }
    }
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
}

includeBuild('../BECameraNeoForge') {
    dependencySubstitution {
        substitute module('nakern.be_camera:bedrockcameralib') using project(':')
    }
}

includeBuild('../BEParticleNeoForge') {
    dependencySubstitution {
        substitute module('net.easecation.beparticle:beparticle') using project(':')
    }
}

includeBuild('../CubeConverter') {
    dependencySubstitution {
        substitute module('com.github.EaseCation:CubeConverter') using project(':')
        substitute module('org.oryxel.cube:cubeconverter') using project(':')
    }
}
